export { default as PlainLayout } from './PlainLayout'
export { default as CenterLayout } from './CenterLayout'
export { default as FrameLayout } from './FrameLayout'
export { Wrapper as FrameLayoutWrapper } from './FrameLayout'
export { default as ErrorLayout } from './ErrorLayout'
